openapi: 3.0.0
info:
  title: Engine API
  description: Contains information about available endpoints
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
      required: [message]

    ProcessInstance:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        businessData:
          type: object
          example: {"orderId": 123, "customer": "John Doe"}
        startTime:
          type: string
          format: date-time
          example: "2023-10-01T12:00:00Z"
        endTime:
          type: string
          format: date-time
          example: "2023-10-01T13:00:00Z"

    TaskHistory:
      type: object
      properties:
        instanceId:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        taskStatus:
          type: string
          example: "COMPLETED"
        taskId:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        taskStartTime:
          type: string
          format: date-time
          example: "2023-10-01T12:00:00Z"
        taskEndTime:
          type: string
          format: date-time
          example: "2023-10-01T13:00:00Z"

paths:
  /process/{processName}/diagram:
    get:
      summary: Workflow diagram
      description: Return workflow diagram in .bpmn format
      parameters:
        - name: processName
          in: path
          description: ID of the process instance
          required: true
          schema:
            type: string
            example: "businessProcess1"
      responses:
        '200':
          description: OK
          content:
            application/xml:
              schema:
                type: string
                example: |
                  <bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL">

                  </bpmn:definitions>
        '404':
          description: Diagram not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /process/{processName}/instance/{id}:
    get:
      summary: Process instance info
      description: Return info about a specific process instance
      parameters:
        - name: id
          in: path
          description: ID of the process instance
          required: true
          schema:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProcessInstance"
        '400':
          description: Invalid UUID format
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '404':
          description: Process instance not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /process/{processName}/instance:
    get:
      summary: Process instances info
      description: Return info about all process instances
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProcessInstance"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /process/{processName}/instance/{instanceId}/task/history/{taskId}:
    get:
      summary: Task history info
      description: Return history info about a specific task
      parameters:
        - name: instanceId
          in: path
          description: Process instance ID
          required: true
          schema:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
        - name: taskId
          in: path
          description: Task ID
          required: true
          schema:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskHistory"
        '400':
          description: Invalid UUID format
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /process/{processName}/instance/{instanceId}/task/history:
    get:
      summary: Task timeline info
      description: Return timeline info about all tasks
      parameters:
        - name: instanceId
          in: path
          description: Process instance ID
          required: true
          schema:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TaskHistory"
        '400':
          description: Invalid UUID format
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '404':
          description: Instance not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /process/{processName}/instance/{instanceId}/task:
    get:
      summary: Tasks info
      description: Return info about all task's for instance
      parameters:
        - name: instanceId
          in: path
          description: Process instance ID
          required: true
          schema:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
        - name: processName
          in: path
          description: Process name
          required: true
          schema:
            type: string
            example: "BuyingProcess or Process3"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TaskHistory"
        '400':
          description: Invalid UUID format
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '404':
          description: Instance not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"