openapi: 3.0.0
info:
  title: Engine API
  description: Contains information about available endpoints
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /workflow/info:
    get:
      summary: Workflow info
      description: Return info about workflow
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    example: "550e8400-e29b-41d4-a716-446655440000"
                  name:
                    type: string
                    example: "Order Processing Workflow"
#                  status:
#                    type: string
#                    example: "ACTIVE"
        '404':
          description: Workflow not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Workflow not found"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "An internal server error occurred"

  /workflow/diagram:
    get:
      summary: Workflow diagram
      description: Return workflow diagram in .bpmn format
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                format: binary
                example: "<bpmn:definitions ...></bpmn:definitions>"
        '404':
          description: Diagram not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Diagram not found"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "An internal server error occurred"

  /processInstance/single:
    get:
      summary: Process instance info
      description: Return info about a specific process instance
      parameters:
        - name: id
          in: path
          description: ID of the process instance
          required: true
          schema:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    example: "550e8400-e29b-41d4-a716-446655440000"
                  businessData:
                    type: object
                    example: {"orderId": 123, "customer": "John Doe"}
                  startTime:
                    type: string
                    format: date-time
                    example: "2023-10-01T12:00:00Z"
                  endTime:
                    type: string
                    format: date-time
                    example: "2023-10-01T13:00:00Z"
        '400':
          description: Invalid UUID format
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid UUID format"
        '404':
          description: Process instance not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Process instance not found"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "An internal server error occurred"

  /processInstance/all:
    get:
      summary: Process instances info
      description: Return info about all process instances
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                      example: "550e8400-e29b-41d4-a716-446655440000"
                    businessData:
                      type: object
                      example: {"orderId": 123, "customer": "John Doe"}
                    startTime:
                      type: string
                      format: date-time
                      example: "2023-10-01T12:00:00Z"
                    endTime:
                      type: string
                      format: date-time
                      example: "2023-10-01T13:00:00Z"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "An internal server error occurred"

  /history/task:
    get:
      summary: Task history info
      description: Return history info about a specific task
      parameters:
        - name: id
          in: path
          description: Task ID
          required: true
          schema:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  instanceId:
                    type: string
                    format: uuid
                    example: "550e8400-e29b-41d4-a716-446655440000"
                  taskStatus:
                    type: string
                    example: "COMPLETED"
                  taskId:
                    type: string
                    format: uuid
                    example: "550e8400-e29b-41d4-a716-446655440000"
                  taskStartTime:
                    type: string
                    format: date-time
                    example: "2023-10-01T12:00:00Z"
                  taskEndTime:
                    type: string
                    format: date-time
                    example: "2023-10-01T13:00:00Z"
        '400':
          description: Invalid UUID format
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid UUID format"
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Task not found"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "An internal server error occurred"

  /timeline/task:
    get:
      summary: Task timeline info
      description: Return timeline info about a specific task
      parameters:
        - name: id
          in: path
          description: Task ID
          required: true
          schema:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  instanceId:
                    type: string
                    format: uuid
                    example: "550e8400-e29b-41d4-a716-446655440000"
                  taskStatus:
                    type: string
                    example: "COMPLETED"
                  taskId:
                    type: string
                    format: uuid
                    example: "550e8400-e29b-41d4-a716-446655440000"
                  taskStartTime:
                    type: string
                    format: date-time
                    example: "2023-10-01T12:00:00Z"
                  taskEndTime:
                    type: string
                    format: date-time
                    example: "2023-10-01T13:00:00Z"
        '400':
          description: Invalid UUID format
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid UUID format"
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Task not found"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "An internal server error occurred"